### ISSUE TITLE
me again

### ISSUE THREAD

**Issue by hsw28** [SeanMcGrath/poshmark-crawler#1]
Hey, me again. Don't know if this is because I have a different version of mechanize than listed in requirements, but I am getting this error when trying to run it: 
```
Traceback (most recent call last):
  File "crawl.py", line 31, in <module>
    main()
  File "crawl.py", line 18, in main
    first_follower = UserFollower.start(printer=printer)
  File "build/bdist.macosx-10.12-intel/egg/pykka/actor.py", line 94, in start
  File "/Users/Hannah/Programming/poshmark-crawler-master/resources.py", line 66, in __init__
    self.br['login_form[username_email]'] = POSHMARK_USER
  File "build/bdist.macosx-10.12-intel/egg/mechanize/_form_controls.py", line 1947, in __setitem__
  File "build/bdist.macosx-10.12-intel/egg/mechanize/_form_controls.py", line 414, in __setattr__
TypeError: must assign a string
```
  

Sorry to be so useless, not familiar with these packages/webcrawling. Also are you at MIT? The now defunct other poshmark crawler had the MIT license on it.

**Comment by SeanMcGrath** [comment]
Though a library mismatch is possible, it looks to me like POSHMARK_USER is undefined. That would imply you haven't set the POSHMARKUSER and POSHMARKPASS [environment variables](http://osxdaily.com/2015/07/28/set-enviornment-variables-mac-os-x/)

**Comment by hsw28** [comment]
No, I set them. I'll look again and see if there is anything I'm missing. thanks! 
| 
 | "How wonderful it is that nobody need wait a single moment before starting to improve the world." 
-Anne Frank |

 

    On Friday, September 29, 2017 8:22 AM, Sean McGrath <notifications@github.com> wrote:
 

 Though a library mismatch is possible, it looks to me like POSHMARK_USER is undefined. That would imply you haven't set the POSHMARKUSER and POSHMARKPASS environment variables—

**Comment by hsw28** [comment]
Figured it out, but it was a combination of things, including that I needed 

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

```
at the start of the code. thanks again works great!!

**Comment by hsw28** [comment]
Spoke a little soon-- problem with logging in after the first go or so. if i go to the site manually it asks me to check a box that I'm not a robot :-p so i think it's locking the bot out

**Comment by SeanMcGrath** [comment]
You are correct. I believe poshmark has a rate limiter on each account, so when the crawler stops working you have to manually do the captcha to reset it. It's a pain but I don't think there's a way around it
